### ISSUE TITLE
Register for CRAN

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/diffeqr#7]
https://ucsb-bren.github.io/env-info/wk07_package.html got us to a useful package. Now let's get it registered. 

Now we should do: http://r-pkgs.had.co.nz/release.html

**Comment by ChrisRackauckas** [comment]
https://win-builder.r-project.org/incoming_pretest/diffeqr_0.1.0_20180422_032730/Windows/00check.log
https://win-builder.r-project.org/incoming_pretest/diffeqr_0.1.0_20180422_032730/Debian/00check.log

@Non-Contradiction is there a way to get the CRAN server to download Julia? Or did you just mention in comments that getting this to build on CRAN wasn't necessary?

**Comment by ChrisRackauckas** [comment]
>So my suggestion is to skip the tests on CRAN's machines as my previous comment

How do you do this? Just make a comment to the CRAN maintainers telling them to ignore the failure?

**Comment by Non-Contradiction** [comment]
For the tests that you don't want to run on CRAN, you can use `skip_on_cran()` like <https://github.com/Non-Contradiction/JuliaCall/blob/master/tests/testthat/test_AD.R>

**Comment by Non-Contradiction** [comment]
You could wrap examples by DONTRUN and the examples will not run on CRAN, also travis and appveyor, for example,
```
#' @examples
#'
#' \dontrun{ ## julia_setup is quite time consuming
#'   julia_do.call("sqrt", list(2))
#'   julia_call("sqrt", 2)
#' }
```

**Comment by Non-Contradiction** [comment]
Great! It seems that `diffeqr` is already on CRAN. <https://CRAN.R-project.org/package=diffeqr>.
And there seems to be problems with the titles of vignettes and the plots are not in vignettes. Is it on purpose? It is possible to include figures in vignettes folder.

By the way, CRAN policy is to update packages once in a month unless important bug fixes. So I guess these problems can be fixed in next CRAN release.
